(setq dir (if load-file-name
              (file-name-directory load-file-name)
            "."))

;; Relies on 'multiple-cursors.
; (load-file (concat dir "/ipe-test-add.el"))
(load-file (concat dir "/ipe-test-adjust.el"))
(load-file (concat dir "/ipe-test-big-tags.el"))
(load-file (concat dir "/ipe-test-char.el"))
(load-file (concat dir "/ipe-test-contents.el"))
(load-file (concat dir "/ipe-test-custom.el"))
(load-file (concat dir "/ipe-test-defn.el"))
(load-file (concat dir "/ipe-test-edit.el"))
(load-file (concat dir "/ipe-test-escape.el"))
(load-file (concat dir "/ipe-test-indent.el"))
(load-file (concat dir "/ipe-test-infix.el"))
(load-file (concat dir "/ipe-test-insert-and.el"))
(load-file (concat dir "/ipe-test-line.el"))
(load-file (concat dir "/ipe-test-list.el"))
(load-file (concat dir "/ipe-test-mc.el"))
(load-file (concat dir "/ipe-test-missing.el"))
(load-file (concat dir "/ipe-test-options.el"))
(load-file (concat dir "/ipe-test-other.el"))
(load-file (concat dir "/ipe-test-update.el"))
(load-file (concat dir "/ipe-test-word.el"))

(ipe-test-run-all)
